const CONFIG = {
    MIN_CONFIDENCE: 0.5,
    RECOGNITION_THRESHOLD: 0.5,
    LATE_THRESHOLD_HOUR: 8,
    LATE_THRESHOLD_MINUTE: 30,
    MIN_FACE_SIZE: 80,
    REQUIRED_CONSECUTIVE_DETECTIONS: 2,
    DETECTION_INTERVAL: 1000,
    MAX_ANGLE: 25,
    MIN_BRIGHTNESS: 0.3,
    MIN_FACE_SCORE: 0.3,
    MAX_DETECTION_DISTANCE: 0.7,
    MIN_LANDMARKS_VISIBILITY: 0,
};

export default  CONFIG;